
Set-StrictMode -Version 2.0
$ErrorActionPreference = "Stop"

# 暴力组合所有可能的路径
$path1 = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\"
$path2 = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VC\Redist\MSVC\"
$path3 = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\"
$path4 = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\"
$path5 = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Redist\MSVC\"
$path6 = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\"

# 检查路径是否存在，找到第一个有效路径
$redist_parent_dir = if (Test-Path -Path $path1 -PathType Container) { $path4 }
elseif (Test-Path -Path $path2 -PathType Container) { $path5 }
elseif (Test-Path -Path $path3 -PathType Container) { $path6 }
elseif (Test-Path -Path $path4 -PathType Container) { $path1 }
elseif (Test-Path -Path $path5 -PathType Container) { $path2 }
elseif (Test-Path -Path $path6 -PathType Container) { $path3 }
else { $null }
# $redist_parent_dir = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\"

$redists = @(Get-ChildItem -Path $redist_parent_dir -Name -Include 14.* -Attributes Directory)

if (!$redists) {
    echo "ERROR: No 14.x redistributable directories found under $redist_parent_dir"
    exit 1
}

$redist_ver = $redists[-1]

$version = (Get-Content build_win64\version.h) -replace '#define SV_VERSION ','' -replace '"','' -replace '-pre.*',''
$wxs = "deploy\win64\sonic-visualiser.wxs"

$in = "$wxs.in"

$redist_dir="$redist_parent_dir\$redist_ver\x64\Microsoft.VC142.CRT"

echo "Generating $wxs..."
echo " ...for SV version $version"
echo " ...for redist version $redist_ver"
echo " ...from $in"
echo ""

if (!(Test-Path -Path $redist_dir -PathType Container)) {
    echo "ERROR: Redistributable directory $redist_dir not found"
    exit 1
}

if (!(Test-Path -Path $in -PathType Leaf)) {
    echo "ERROR: Input file $in not found"
    exit 1
}

(Get-Content $in) -replace '@VERSION@', $version -replace '@REDIST_VER@', $redist_ver -replace '@W@', '<!-- DO NOT EDIT THIS FILE: it is auto-generated -->' | Out-File -encoding ASCII $wxs

echo "Done"



