name: Release
on:
  push:
    tags:
      - "V0.*"

jobs:
  build:
    runs-on: windows-2022

    strategy:
        matrix:
          toolset: ["14.44"]

    steps:
      - uses: actions/checkout@v3


      - name: Download and extract OpenSSL
        run: |
          $url = "https://slproweb.com/download/Win64OpenSSL-3_0_12.zip"  # 免安装版
          Invoke-WebRequest -Uri $url -OutFile "openssl.zip"
          # 解压到C:\openssl-3.0
          7z x openssl.zip -oC:\openssl-3.0 -y
          # 验证文件
          Test-Path "C:\openssl-3.0\Win64OpenSSL-3_0_12\bin\libssl-3-x64.dll"
          # 移动到目标路径（可选，简化路径）
          Move-Item "C:\openssl-3.0\Win64OpenSSL-3_0_12\*" "C:\openssl-3.0" -Force
          echo "C:\openssl-3.0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Verify
        run: openssl version

      
      - uses: ProjectSavanna/setup-sml@v1.2.0
        with:
          smlnj-version: '110.99.4'
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: ${{ matrix.toolset }} # 指定 14.X 工具集版本
          vsversion: '2022'

      - name: install-meson
        run: pip install meson ninja

      - name: repoint
        run: ./repoint install

      - name: Run build script
        run: |
          deploy\win64\build-and-package.bat

      - name: Create release package
        run: |
          mkdir release_package
          xcopy /E /I build_win64 release_package\build_win64
          7z a -tzip "sonic-visualiser-release.zip" "release_package\*"

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.ref_name}}
          release_name: Release ${{github.ref_name}}
          filess: sonic-visualiser-release.zip
          token: ${{secrets.GITHUB_TOKEN}}
